version: "3"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app/
      - /app/node_modules
    command: yarn dev
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.9-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
